// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeDownPath() {
  return window['go']['controller']['App']['ChangeDownPath']();
}

export function CreateShareLinkInfo(arg1) {
  return window['go']['controller']['App']['CreateShareLinkInfo'](arg1);
}

export function DeleteRetry(arg1) {
  return window['go']['controller']['App']['DeleteRetry'](arg1);
}

export function DownFIle(arg1) {
  return window['go']['controller']['App']['DownFIle'](arg1);
}

export function DownFilePre(arg1) {
  return window['go']['controller']['App']['DownFilePre'](arg1);
}

export function DownRetry(arg1) {
  return window['go']['controller']['App']['DownRetry'](arg1);
}

export function GetAuthorityCount() {
  return window['go']['controller']['App']['GetAuthorityCount']();
}

export function GetConfig() {
  return window['go']['controller']['App']['GetConfig']();
}

export function GetDownListDetail() {
  return window['go']['controller']['App']['GetDownListDetail']();
}

export function GetFileList(arg1) {
  return window['go']['controller']['App']['GetFileList'](arg1);
}

export function GetFileOtherList(arg1, arg2) {
  return window['go']['controller']['App']['GetFileOtherList'](arg1, arg2);
}

export function GetTopList(arg1) {
  return window['go']['controller']['App']['GetTopList'](arg1);
}

export function UpdateConfigItem(arg1) {
  return window['go']['controller']['App']['UpdateConfigItem'](arg1);
}
