// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {netfile} from '../models';
import {controller} from '../models';

export function ChangeDownPath():Promise<string>;

export function CreateShareLinkInfo(arg1:string):Promise<number>;

export function DeleteRetry(arg1:number):Promise<void>;

export function DownFIle(arg1:Array<download.DownDetail>):Promise<void>;

export function DownFilePre(arg1:Array<netfile.FileListInfo>):Promise<number>;

export function DownRetry(arg1:number):Promise<void>;

export function GetAuthorityCount():Promise<number>;

export function GetConfig():Promise<{[key: string]: string}>;

export function GetDownListDetail():Promise<Array<download.DownDetail>>;

export function GetFileList(arg1:string):Promise<Array<netfile.FileListInfo>>;

export function GetFileOtherList(arg1:string,arg2:string):Promise<string>;

export function GetTopList(arg1:string):Promise<Array<string>>;

export function UpdateConfigItem(arg1:controller.ConfigItem):Promise<void>;
